### ISSUE TITLE
Re-checking flags

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#131]
Flags may become outdated over time. There should be some periodic check to ensure that flags are still valid.

**Comment by Gyukat** [comment]
Discussion: 
Josh: Sanity checks are run per ingest, because we are checking reports. I think that's a good behaviour. What we can do is some cron job, which runs weekly and do the flag check sometime, when the system is not frequently used, overnight or something. It's kind of resource heavy operation so I wouldn't recommend to run it too often.

Kathryn Mathe
20:26 3 Mar
Still you might want to "re-run" the sanity checks so you don't create inconsistency within a single submission response...like we saw the other day. Basically, record number 2, "solved" the flag from record number 1. You have to manage to remove that flag before you finalise the bulk submission and send out warnings.

József Gábor Bóné
20:33 3 Mar
But that was because of the bug, that I haven't set the flag to 'None' when I did the flag check for an existing report.

**Comment by JoshBone** [comment]
Can you prepare a list of events triggering flag check rerun?

**Comment by Gyukat** [comment]
TO DISCUSS WITH COLIN

**Comment by ctueck** [comment]
System to clear (and keep cleared) flags works now.

Otherwise to be addressed by general review of validation & flagging - new issue to be created.
