### ISSUE TITLE
Add flags to ETER imported records 

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#134]
Institution records that are created based on ETER records sometimes have no QF-EHEA levels. Add low-level flag to institution records created from ETER records that have no QF-EHEA levels.  Two choices a) add flag for all during transformation; b) add flag only at the point that the record is matched during a submission ingest.  There is no need to notify the user of this flag as the flag is not caused by the user's data but only triggered by the match.

**Comment by JoshBone** [comment]
Should I include some flag message as well?

**Comment by Gyukat** [comment]
This could be good but would be part of ETER harvest workflow.
