### ISSUE TITLE
 Institution record created without complete data

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#135]
Did you fix this already? If a local ID is entered in the CSV, the validity check does not catch non-existent records if the record already exists.  The local ID needs to be checked to see if it matches up before the record is accepted into the system with incomplete data.

**Comment by Gyukat** [comment]
Will try to recreate...it was tricky but not good.

**Comment by JoshBone** [comment]
I think [https://github.com/EQAR/eqar_backend/commit/0b2acf85d0efdbe4f8ee162979d0a1c8da044434](this commit) should fix this as well.

**Comment by JoshBone** [comment]
I think I can close this by now...

**Comment by Gyukat** [comment]
okay, I'll admit that i have lost the plot with it a bit.
