### ISSUE TITLE
Local Institution ID Submission Problems

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#145]
PTI: Local ID double submission | An agency can submit the same local ID for two different Institutions. This should be a unique combination.  ID>Agency>Institution

PTII: Local ID double submission. When you try to use a local ID that has been successful submitted for multiple institutions, you get a 500 server error.  This should be a unique combination.  ID>Agency>Institution

**Comment by JoshBone** [comment]
I got your point, but the thing is, that it's not simple db uniqueness question. :)
It's the question that the combination of local_id and Agency shouldn't be unique throughout the system. So I should check when the submission happens. The question is, what should be error message, if someone tries to submit an existing local_identifier. (And it gets even trickier, because I should raise this error only, when an institution record is being created :) )

**Comment by JoshBone** [comment]
On the other hand... I have an interesting question. 
How can someone submit the same local identifier to a different institution through submission? 
Isn't the identification should happen like deqar_id -> eter_id -> local_id ?

**Comment by JoshBone** [comment]
Btw. - Isn't this related to #135 ?

**Comment by Gyukat** [comment]
You can always "submit" a local id...at this point it simply records the ids in the institution records.  It is only at the point of trying to use the ids for identification purposes that the problem arises---pt 2 above.

**Comment by ctueck** [comment]
Noticed that ASHE submitted a number of reports via API and created duplicates of institutions records in the submission...

So I noticed there are a number of current problems:

- it seems in submission, only identifiers linked to the agency and with resource "local identifier" are used - everything else cannot be used for identification of an institution.
- the uniqueness condition is not enforced currently for identifiers not linked to an agency. I was curious, and it seems to be because the UNIQUE constraint considers any row where one of the columns involved is NULL as unique...

**Comment by JoshBone** [comment]
"it seems in submission, only identifiers linked to the agency and with resource "local identifier" are used - everything else cannot be used for identification of an institution." 
This shouldn't be the case. 

The code responsible for the check is here:
https://github.com/EQAR/eqar_backend/blob/233ef06919e664a77b4685beee800a13d7bafadd/submissionapi/populators/institution_populator.py#L74-L87

So it checks for the combination of identifier / resource (which defaults to 'local identifier' if there wasn't any submitted) / agency. 

Which are the duplicate institution records?

**Comment by ctueck** [comment]
Hm, but it always includes the agency in the match, doesn't it? But the identifier might come from ETER, us or someone else, and have agency set to NULL.

And is this the code that's double-checking for existing records before creating a new one? And does it actually get here if I supply a local_identifier, but not a basic record?

**Comment by JoshBone** [comment]
Django Suit is not going to the same pipeline as submission... :)
That's really just a frontend to the actual database fields. 

I understand the first suggestion - So what the identification should do apparently. If the resource is local_identifier it should include the agency, if it's anything else, it shouldn't. 

> And is this the code that's double-checking for existing records before creating a new one? And does it actually get here if I supply a local_identifier, but not a basic record?

Yes. If you check the Institution populator class: https://github.com/EQAR/eqar_backend/blob/233ef06919e664a77b4685beee800a13d7bafadd/submissionapi/populators/institution_populator.py
It's starting with the identification procedure. (Obviously this is called after the validation of the incoming data. But yes, it should be triggered)

**Comment by ctueck** [comment]
> I understand the first suggestion - So what the identification should do apparently. If the resource is local_identifier it should include the agency, if it's anything else, it shouldn't.

Yes, for the current data model that would make sense. (But since we agreed to change it either way, it might change the issue of course.)

**Comment by JoshBone** [comment]
Meanwhile I removed agencyID from those institution records, where it registered the agency identifier together with the 'national identifier'.

**Comment by ctueck** [comment]
Yeah, great, tested with the German IDs and a custom resource string, works well.

The Croatian HEIs are a bit of a mess following tests and pre-loading identifiers, but I'll clean it up over the weekend in dialogue with Tomislav.

Just one issue: we have a few (128, to be exact) non-unique identifiers in the "national identifier" namespace. Probably a good solution would be to change "national identifier" into the alpha-3 code of the respective country, and it should be solved (provided the identifiers we imported from ETER are unique within a given country, who knows...).

If you both agree, I'm happy to do that some time during the weekend, too.
