### ISSUE TITLE
include expired reports & indicator in /browse/reports/*

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#152]
After feedback from Slik, it would be preferable if the `/browse/reports/*` endpoints always return everything (incl. old reports, i.e. as if history=true were passed), and include a boolean indicator for each report whether it is still valid (= before expiry date or less than 6 years old if it has no expiry date).

**Comment by JoshBone** [comment]
Whoops... 
I forgot to check if valid_to is set. :)
Btw. github is set that when I do a pull request merge it automatically closes the issue. Is it okay like this? I don't mind to have issues re-opened. :)

**Comment by ctueck** [comment]
Sounds good and logical to both Kate & me, the auto-close.

And intuitively I thought if there's still an issue, re-opening is what I should do. So will keep doing that if needed. ;)
