### ISSUE TITLE
/browse/institutions/{id} : include country id (or even full record)

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#157]
In countries array, frontend will need the country id to pull related data (QA requirements).

Alternatively, unless it would be bad design, the array could also include the `qa_requirements` array from the country record, or even the full thing. (This would save one API call: building a mock up for Slik I realise they'll probably make 4 calls for one institution page: to `/browse/institutions/{id}/`, `/browse/countries/{id}/`, `/browse/reports/programme/by-institution/{institutionID}` and `/browse/reports/institutional/by-institution/{institutionID}`)

**Comment by JoshBone** [comment]
Swagger is updated as well...

**Comment by JoshBone** [comment]
Swagger is updated as well...
