### ISSUE TITLE
/browse/institutions/{id} - with history as default

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#163]
Could you also make history=true the default here, so that all old names are included? Thx.

**Comment by JoshBone** [comment]
History switch affects all the historical data display - countries, qf ehea levels and the historical fields. 
A) Should I include all of these as default?
B), or should I remove institution names from this context?

**Comment by ctueck** [comment]
I think A is fine and also simpler, right?

It won't hurt to have all this info there by default, it won't create much overhead. Most of these things don't change terribly often.
