### ISSUE TITLE
/browse/reports/*/by-institution/{id}/ : include joint programme partners in institution_relationship_context?

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#165]
**Ignore for now** - this is neither urgent, nor sure whether it's a good idea, but #162 made me think of this:

Should we add to institution_relationship_context those other institutions that are involved in a joint programme? (Or more broadly, other institutions related to the same report.)

Currently, when we have an accreditation of a joint programme, it is not visible which are the other institution(s) involved, but of course that might be interesting for users to see in the frontend.

Anyway, this was never in our mock up and we can safely ignore this now, but should discuss and possibly get back when we are discussing enhancements later this year.

**Comment by Gyukat** [comment]
I think this would be complicated because the relationship is through a programme.  We might think about it in the context of developing the programme record.

**Comment by Gyukat** [comment]
See related: https://github.com/EQAR/eqar_backend/issues/161

**Comment by ctueck** [comment]
Was done by https://github.com/EQAR/eqar_backend/commit/5292c248432d3e92897d15b1a58de35c031b2226
