### ISSUE TITLE
Always "user" instead of actual username

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#173]
I always see "user", and not my actual username:

![screenshot](https://user-images.githubusercontent.com/37637883/38989374-f865906c-43d6-11e8-953c-c669e157c30b.png)

**Comment by JoshBone** [comment]
https://github.com/EQAR/eqar_frontend/pull/54 - fixes this.
Just for the sake of easiness can we put the fronted related issues to the eqar_frontend repository? 
That way I can close those with a direct code commit. :)
Thank you.

**Comment by ctueck** [comment]
Sure. Sorry, did this in a rush without realising it's a different repository.
