### ISSUE TITLE
[DjangoSuit & general] target for EQAR decision files

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#189]
Reports submitted by agencies automatically go into subdirectories named as the agency acronym.

Please set default target for uploaded EQAR decision (on agencies) files to the `EQAR/` directory - this is where I imported existing ones and would be good to have them in a separate place.

(Applies to the DjangoSuit now and the admin UI later on.)

**Comment by JoshBone** [comment]
I've pushed it to the test, can you try if it works as expected?
