### ISSUE TITLE
/browse/institutions/ - set history default to true

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#191]
Institution browsing should include institutions that have only expired reports by default.

Currently we have a discrepancy: `/browse/countries/by-reports/` correctly includes historic reports in counter, e.g. Belgium at <https://www.eqar.eu/qa-results/> with 5 institutions, but <https://www.eqar.eu/qa-results/?query=&country=17> shows only 3.

**Comment by JoshBone** [comment]
Interestingly it's fixed on the backend, but the qa-results site doesn't pick up the changes. 
(At least for me at the moment) - https://backend.deqar.eu/webapi/v1/browse/institutions/?country=17
