### ISSUE TITLE
Project kick-off meeting

### ISSUE THREAD

**Issue by gygabor** [EQAR/eqar_backend#2]

**Comment by JoshBone** [comment]
Collecting questions for the kick-off meeting in Brussels.
https://docs.google.com/document/d/1Vtkgm2fuzHHm40lCcIv4Tv8JuHmnvNJWN0LQVqCzA1w

**Comment by JoshBone** [comment]
Notes highlighted with orange, tasks highlighted with yellow were written in the Google Doc.
