### ISSUE TITLE
[FileHarvester] - Permalinks giving back empty filenames

### ISSUE THREAD

**Issue by JoshBone** [EQAR/eqar_backend#211]
If the link is a permalink, then filename will be empty. 
We can use the filename from the response header in content-disposition.

**Comment by JoshBone** [comment]
Something like this can be a good option:

`import re
d = r.headers['content-disposition']
fname = re.findall("filename=(.+)", d)`

**Comment by ctueck** [comment]
I see that in the ANQA example there is a Content-disposition header. But does the HTTP standard require that there's one, i.e. can we rely on it?

Also, I found that the missing file name as such is not the problem, but mainly the missing extension. 

The permalink itself works well, as it returns a Content-type header.

But the harvester safes the file and not the Content-type. In all normal scenarios (where there is a file name with a fitting extension) it's fine, and when nginx delivers the file to the user it sets the right Content-type based on the extension.

But if there's no extension, nginx can't know.

I came across <https://docs.python.org/3.2/library/mimetypes.html#mimetypes.guess_extension> - would it be an idea to guess the "right" extension and add it if there isn't any?

**Comment by ctueck** [comment]
There were some similar problems during the test, e.g. some reports from SQAA had a name but no extension, check this example:

```
colin@EQAR-MBA-CT:~$ curl -v -XHEAD "https://backend.deqar.eu/reports/SQAA/20180320_1056_295"
[...]
< HTTP/1.1 200 OK
< Server: nginx/1.10.3 (Ubuntu)
< Date: Thu, 07 Jun 2018 22:30:13 GMT
< Content-Type: application/octet-stream
< Content-Length: 367572
< Last-Modified: Tue, 20 Mar 2018 10:56:50 GMT
< Connection: keep-alive
< ETag: "5ab0e8f2-59bd4"
< Accept-Ranges: bytes
```

They don't have a proper content-type, since no extension allows to determine it.

The original URL, however, serves a correct content-type:

```
colin@EQAR-MBA-CT:~$ curl -v -XHEAD "http://www.nakvis.si/sl-SI/Content/GetFile/295"
[...]
< HTTP/1.1 200 OK
< Cache-Control: private
< Content-Length: 367572
< Content-Type: application/pdf
< Server: Microsoft-IIS/7.5
< X-AspNetMvc-Version: 3.0
< Content-Disposition: attachment; filename="Koncno porocilo UL 2013.pdf"
< X-AspNet-Version: 4.0.30319
< X-Powered-By: ASP.NET
< X-Powered-By-Plesk: PleskWin
< Date: Thu, 07 Jun 2018 22:32:51 GMT
```

**Comment by JoshBone** [comment]
Yep... 
Good idea with the Content-type header. 

> Also, I found that the missing file name as such is not the problem, but mainly the missing extension.

I was thinking of a fallback model, where:
- if the filename can be resolved from the URL, then it's resolved
- if not, then the existence of Content-disposition / filename is checked and kept
- if neither, then only the timestamp will be the filename. 

And yes, in the case of the latter two, Content-type header should be checked for the correct extension. I'll improve the file_downloader according to these.

**Comment by ctueck** [comment]
Yes, fallback model sounds excellent.

I'm wondering whether filename in content-disposition should override the last component of URL? Does HTTP standard give an answer to that?
