### ISSUE TITLE
/browse/institution - include institutions where parent or children have reports

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#217]
Similar to the behaviour of the /browse/reports/*/by-institution endpoints, the institution search results should also include institutions where parent or children institution(s) have a QA report.

E.g. search should also show [University of Zagreb](https://www.eqar.eu/qa-results/institution/?id=1270), even if only several of its children have reports, and show also all children of [Normandie université](https://www.eqar.eu/qa-results/institution/?id=4560), because of the report for their parent.

**Comment by JoshBone** [comment]
I can, but it will be again slowing down the institution search, since it's an another join query (even if it's recursive...) And how this will affect all the filters? So if the parent has reports which are fulfilling the search criteria or the children?

**Comment by ctueck** [comment]
Well, I'd say let's do it if it doesn't slow it down really bad. For the moment, all queries seem to work reasonably fast (except #218).

Re. the other filters I think it should be the same logic: institutions should show up if their (direct) parents/children have reports that match the other search criteria. (Like they show up if their "own" reports match.)

**Comment by Gyukat** [comment]
We should extend this logic also to the historically related records when the validity date extends beyond the historical merger/split/absorption.  In this case, we are now asking that the report will show up on the later record.  It should also show up in the search.

**Comment by Gyukat** [comment]
Here is our original spec. for Institutional Relationships
[Institutional Relationships_2018-04-04.docx](https://github.com/EQAR/eqar_backend/files/2210287/Institutional.Relationships_2018-04-04.docx)

See section II: Update to search functionality:

- The search domain should include all institution names and other searched elements, including for historical names, inactive institutions or child institution records.

> STILL TRUE


- The results list should include all results obtained through search domain. Institutions should only show up in the results list through a direct hit on their name/data—not through relationships. 

 > ADAPTED - HIERARCHICALLY RELATED INSTITUTIONS SHOULD SHOW UP ACCORDING TO THE FOLLOWING CRITERIA:
> --for hits in any name field, 
> ---all CHILD institutions should show up on a hit for the PARENT
> ---a PARENT institution should show up on a hit for the CHILD
> ---SIBLINGS **do not** show up automatically as a hit. 
> --for hits on country, these should happen automatically if applicable, no need to adjust search
> --for hits on city, these should happen automatically if applicable, no need to adjust search. (@ctueck please okay this last rule; city is not a required field so there will be some asymmetry.)
 
> ADAPTED - HISTORICALLY RELATED INSTITUTIONS SHOULD SHOW UP ACCORDING TO THE FOLLOWING CRITERIA:
> --for hits in any name field, 
> ---all TARGET institutions should show up on a hit for the SOURCE
> ---a SOURCE institutions should show up on a hit for the TARGET
> ---no record that is two steps/relationships removed should show up on a hit:
> ----e.g. a hit for a TARGET should not result in another TARGET of the same SOURCE or a SOURCE of the same SOURCE; 
> ----e.g. a hit for a SOURCE should not result in another SOURCE of the same TARGET or a TARGET of the TARGET.
> --for hits on country, these should happen automatically if applicable, no need to adjust search
 > --for hits on city, these should happen automatically if applicable, no need to adjust search. (@ctueck please okay this last rule; city is not a required field so there will be some asymmetry.)

> **Basic effect: you will get hits on exactly those records you see linked from primary institution that produced a hit.**

**Comment by Gyukat** [comment]
As a rule, we only show records for institutions that include reports.  And yet...we have examples of institutions showing up through the search interface that have no reports (not even historical reports).  I think they are related institutions.  Can you explain to me a bit the logic here?

https://www.eqar.eu/qa-results/institution/?id=4113

**Comment by JoshBone** [comment]
Parallel to that please tell Slik that if the API gives you back 404, that a record doesn't exists, they should also show 404 page, not an empty one like this:
https://www.eqar.eu/qa-results/institution/?id=9999

**Comment by Gyukat** [comment]
We should discuss this as well....

**Comment by Gyukat** [comment]
On the results list, an institution that is the child of several institutions should display separate for each parent institution.  (Note: this could lead to multiple hits for a single entity.)  Currently, these are all gathered in a single entry and confusing 
<img width="601" alt="Screen Shot 2019-03-12 at 15 59 51" src="https://user-images.githubusercontent.com/33084539/54210507-e90f4a80-44df-11e9-96b8-4022fe9cf3b6.png">
<img width="822" alt="Screen Shot 2019-03-12 at 15 59 36" src="https://user-images.githubusercontent.com/33084539/54210508-e90f4a80-44df-11e9-997b-fd320c2f3a38.png">
