### ISSUE TITLE
Merged/Absorbed entities should not have an end date on the final name

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#219]
You have been stamping the name of historical entities with an end date.  In this case, the records display without any header and with the original name as a previous name.  For the meantime, we should remove the valid_until dates on the names of closed entities (also countries).  We can discuss more later.

**Comment by ctueck** [comment]
This is partly due to how OrgReg data is structured, partly due to me misunderstanding when copying data over. ;)

Will fix it and remove the end dates from the ultimate names of closed institutions (and same for locations, it's an equivalent issue there).

**Comment by ctueck** [comment]
End dates are removed, now every institutions has one and only one "current" name.
