### ISSUE TITLE
Two records created for same institution (different name but same URL)

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#221]
We note that there is a case where the system created a new record for an institution when the name version submitted was different but the URL was the same.  This shouldn't happen.

<img width="1276" alt="screen shot 2018-06-28 at 15 31 21" src="https://user-images.githubusercontent.com/33084539/42037330-6ccbacd2-7ae8-11e8-90f3-39aecae7de19.png">

**Comment by Gyukat** [comment]
See also: https://github.com/EQAR/eqar_backend/issues/209

**Comment by Gyukat** [comment]
We should discuss this!

**Comment by JoshBone** [comment]
Mmmm... 
In the submission log I can see only trace for Ogarev Mordovia, but no record for National Research Ogarev Mordovia... Can it be, that the later was imported from OrgReg by any chance and not went through our workflow?

**Comment by JoshBone** [comment]
https://github.com/EQAR/eqar_backend/blob/8a9c40b81bbbb96d31e6429d0da4c3122db21e17/submissionapi/populators/institution_populator.py#L56-L145 - Here is the logic, how institutions are identified. So it goes sequential, and if there is any match the institution is resolved. Which means, that same URLs shouldn't exists if institutions were added via submission...

**Comment by Gyukat** [comment]
What does this mean?  Should we remember to include a similar pipeline in our Yearly updates?
