### ISSUE TITLE
Doubling of english name versions

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#222]
In some cases (e.g. Russian records), the EN name is doubled.   I am not sure why:

<img width="779" alt="screen shot 2018-07-10 at 13 38 54" src="https://user-images.githubusercontent.com/33084539/42507786-ab9da6a6-8446-11e8-8db9-d61536e0d027.png">

**Comment by ctueck** [comment]
Could we introduce a general check that one cannot add a name version (through any method) that is equal to name_official, name_english or an already existing name version?

**Comment by Gyukat** [comment]
Josh, another one just appeared...does it relate to the cyrillic official names by chance?

<img width="1096" alt="screen shot 2018-07-17 at 15 12 24" src="https://user-images.githubusercontent.com/33084539/42819471-f427b082-89d3-11e8-96f5-7c05f9dfc128.png">

**Comment by Gyukat** [comment]
Still need to check this.

**Comment by Gyukat** [comment]
To discuss

**Comment by JoshBone** [comment]
In case of Jinan University:
They submitted the name as CSV and once it was name_official, then name_english, after that they submitted it as name_official_transliterated.

**Comment by Gyukat** [comment]
So, it is a pipeline problem...let's remember to fix that in the pipeline.  We should not collect alternative names.  We might also check the identifiers

**Comment by Gyukat** [comment]
Josh, can we clean the institution records related to NCPA automatically????  OR Should I go through and do it myself.

**Comment by JoshBone** [comment]
Sent the link to the NCPA and the pipeline fix will be further discussed in issue #250

**Comment by Gyukat** [comment]
Got it!!!
