### ISSUE TITLE
Reports made for an institution that has been merged, absorbed or split

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#223]
If a report's validity date extends beyond an historical "event" (i.e. merger, split, absorption, spin off), then the report should show up on both the original institution record and also on the later related institution records.  (The search should also reflect this logic.)

**Comment by Gyukat** [comment]
(Related issue: https://github.com/EQAR/eqar_backend/issues/217)

**Comment by JoshBone** [comment]
Somehow it would be nice to have some examples how hits should look like / appear. 
So let's say someone searches for a string which exists in a parent unit name and one of the child unit's name. Currently you are getting two hits...

How this should be changed?:
- There should be only the parent one with only those child listed where the search gives results?
- All children should be listed?

What about the rest of the filters?

**Comment by Gyukat** [comment]
I have dealt with the above in the related card: #217 

Regarding this particular request, I am also attaching the former spec.  
[Institutional Relationships_2018-04-04.docx](https://github.com/EQAR/eqar_backend/files/2210447/Institutional.Relationships_2018-04-04.docx)

The relevant section is: III. Display of related institution information in institution records

When an institution with no active/valid reports is hit then you will simply retrieve a record with no reports displayed and you will have to activate the historical function to see old reports.

> THIS WILL CHANGE.  (WE ARE DEFAULTING TO SEEING HISTORICAL REPORTS NOW...NOT IMPORTANT FOR YOU I THINK.)

Relationships of historical type (type 2, 3, 4) should be displayed simply as a link from the record with note beneath. Label can read “Historical note” followed by bulleted  list:

> CHANGED TO "HISTORICAL RELATIONSHIPS"

- on type 2 source record: Succeeded by [linked: target institution] ([date]).  
- on type 2 target record: Succeeded [linked: source institution] ([date]).  
- on type 3 source record: Absorbed [linked: target institution] ([date]).  
- on type 3 target record: Was absorbed by [linked: source institution] ([date]).  
- on type 4 source record: Spun off [linked: target institution] ([date]).  
- on type 4 target record: Was spun off from [linked: source institution] ([date]).  

> SLIGHTLY CHANGED FORMAT, BUT MORE OR LESS TRUE.

- Each entry is followed on next line by [relationship note] string.

> NOT SURE IF THIS WAS DONE BY SLIK.

- Multiple relationships (even on the same date) will be represented as separate entries.
- Note: historical names will also be clustered according to date and included in this display as
-- Known as [historical name official]/[historical name english]/[historical name alternative] (until [date])

> **NEW SPECS. FOR SHOWING HISTORICALLY RELATED REPORTS ON INSTITUTION PAGES.** 
> Should include reports from:
> - On SUCCEEDING TARGET record: all PRECEDING SOURCE record institutional and programme reports whose report validity extends beyond the succession, merger or split date.  (Note, this **does not** work in inverse as it would violate the relationship logic.)
> - On ABSORBing SOURCE record: all ABSORBED TARGET record institutional and programme reports whose report validity extends beyond the absorption date.  (Note, this **does not** work in inverse as it would violate the relationship logic.)
> - On SPUN OFF **TARGET record**: all SOURCE of SPIN OFF record institutional and programme reports whose report validity extends beyond the spin off date. (Note, this **does not** work in inverse as it would violate the relationship logic.)
> **- In ALL cases, these are effectively earlier records whose reports show up on later records.**
> - Display of Reports should follow naming convention used in hierarchical records.

**Comment by Gyukat** [comment]
Here is an example of how reports might show up on a historically related record:

Sibelius (my favourite absorbed institution) has a 2013 report that is valid until 2019
- https://www.eqar.eu/qa-results/institution/?id=4269

Sibelius was absorbed by University of the Arts Helsinki in 2013.  
- https://www.eqar.eu/qa-results/institution/?id=866

The report was still valid at the moment that Sibelius was absorbed by University of the Arts (actually the date of absorption PRECEDES the report, which is a bit strange)...therefore the Sibelius report should show up on the University of the Arts Page (under a heading that includes the name Sibelius: "Institutional audit, Sibelius Academy (by FINEEC)"

**Comment by Gyukat** [comment]
Let's check through this!

**Comment by Gyukat** [comment]
The reports show up, but the data is lacking the `institution_relationship_context` information (name, etc.).

**Comment by Gyukat** [comment]
Still a problem...for instance, the report from Sybillius shows up as a "normal" report for University of the Arts Helsinki.

<img width="1024" alt="screen shot 2018-10-03 at 22 12 34" src="https://user-images.githubusercontent.com/33084539/46436702-d1c27900-c759-11e8-9a1e-705e22180af9.png">

**Comment by Gyukat** [comment]
We don't see this...it didn't work on the record that we use as an example...https://www.eqar.eu/qa-results/institution/?id=4269

**Comment by ctueck** [comment]
@JoshBone Sorry, I realise the info is there but just not "consumed" by the template. But I now remember the reason, I think we discussed also in Vienna: hierarchical info so far came out of the `institution_relationship_context` array, while all info (hierarchical relations, historical relations, and institutions with whom a joint programme is offered) is in the new `institutions` array.

So that is definitely better and more flexible, it just misses one info: the type of relationship (e.g. `institution_relationship_context` included parent or child). So it would be great if we could simply add parent, child, historic, joint_programme, ... or some sort of clarifier to see what is the relationship.

I could then change the template to use all info from `institutions` and we can ultimately retire `institution_relationship_context`.

**Comment by Gyukat** [comment]
REMINDER!!!!  PLEASE LOOK OVER THIS!

**Comment by Gyukat** [comment]
WE have found a record that breaks this rule.  See the report: https://www.eqar.eu/qa-results/search/by-institution/institution/?country=Austria&id=15

The 2013 report FINEEC is related to the University of Graz, which this institution spun off from in 2004.  The report should only appear IF it was valid before the spin off OR after a MERGER.
