### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#226]
Search domain should include Institution Record: all name(s), city, country... search should default to “and” search—not phrase search.  Search should be article and preposition agnostic (at least in English)

**Comment by Gyukat** [comment]
See my question about the search #239

**Comment by Gyukat** [comment]
We still need to do this, I think.

**Comment by Gyukat** [comment]
THIS IS PENDING...CAN WE DO IT?!  I THINK SLIK HAS FIXED FROM THEIR SIDE.

**Comment by Gyukat** [comment]
We can see that it is still set as "AND" but there are also other problems...like this:  

<img width="793" alt="screen shot 2018-10-03 at 17 36 06" src="https://user-images.githubusercontent.com/33084539/46421677-e93a3b80-c732-11e8-81e6-3fb4a37a792e.png">

**Comment by JoshBone** [comment]
This is waiting for my solr implementation... I can't promise it by Friday, but rather for the weekend.

**Comment by Gyukat** [comment]
I will be in Riga for another "user testing" on Saturday afternoon.  So, it would be good to have it up and functioning by then because the OR search always gets people.  
(Btw, I hope the system can handle 50 people all at once!  Cross fingers!)

**Comment by Gyukat** [comment]
search: university zagreb

 still doesn't give "university of zagreb" as result.
