### ISSUE TITLE
Include "other" among QF-EHEA levels

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#230]
We can add a new value to the list...is there other programming around it that should be updated?

**Comment by JoshBone** [comment]
Nope.
But you need to assign a code as well, because that's what's used in the CSV upload.

**Comment by Gyukat** [comment]
Make it 4


0 => short cycle || 1 => first cycle || 2 => second cycle || 3 => third cycle || 4 => other

This is for both Institution and Programme related QF-EHEA tables.

**Comment by JoshBone** [comment]
Added...

**Comment by Gyukat** [comment]
checked
