### ISSUE TITLE
Agency/Country records - information on filtered number of institution and reports

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#231]
We are adding links to filtered lists from Agency and Country pages back to search results.  Here are the instructions for Slik.

"We would like to add and update  statements in orange linked back to filtered search results.  Do not underline the text in orange block statements, we can treat these statements as a button. Do not include these statements when there are no linked records.  (API end points will be updated to include this information.)

In Agency record:

1) Include general statement "View # institutions with # reports" directly under the Agency name header (and after all name version).  This should link to a filtered results list of institutions by agency. (Note: we should move the label: "Substantially compliant with ESG" under all the name versions as well.)

2) Include statement "View # institutions with # reports" under each agency activity at the bottom of the Agency page.  This should link to a filtered list of institutions by agency activity.

In Country record:

1) Include general statement "View # institutions with # reports" directly under the Country name header.  This should link to a filtered results list of institutions by country.

2) Include statement "View # institutions with # reports" under each agency name at the bottom of the Country page.  This should link to a filtered list of institutions by country and agency.

"

**Comment by JoshBone** [comment]
If you don't mind I'd create different endpoints for the statistics, because i can have a simple count query and I don't have to merge the results with the detail-data.

**Comment by Gyukat** [comment]
Do what you think is best...as long as they can incorporate it in the entries where needed.

**Comment by JoshBone** [comment]
> Include statement "View # institutions with # reports" under each agency name at the bottom of the Country page. This should link to a filtered list of institutions by country and agency.

Is this by agency focused country, or agency based in, or both?

**Comment by JoshBone** [comment]
Deployed to the test:
https://backend.test.deqar.eu/webapi/v1/browse/stats/by-agency/35/
https://backend.test.deqar.eu/webapi/v1/browse/stats/by-country/142/

Question for the next one. 
In the list of agencies the statistics should be based on the agency, or the agency and country as well?

**Comment by Gyukat** [comment]
In Agency record:
 - Include general statement "View # institutions with # reports" directly under the Agency name header (and after all name version). This should link to a filtered results list of institutions by agency. (Note: we should move the label: "Substantially compliant with ESG" under all the name versions as well.)

THIS IS A FILTERED LIST OF INSTITUTIONS WITH REPORTS BY THE AGENCY.  LIST THE NUMBER OF INSTITUTIONS WITH AGENCY'S REPORTS AS WELL AS THE NUMBER OF REPORTS BY THE AGENCY.

- Include statement "View # institutions with # reports" under each agency activity at the bottom of the Agency page. This should link to a filtered list of institutions by agency activity.

THIS IS FURTHER FILTERED FROM ABOVE BY THE AGENCY'S ACTIVITY.  SO, A FILTERED LIST OF INSTITUTIONS WITH REPORTS UNDER A CERTAIN ACTIVITY BY THE AGENCY...

In Country record:

- Include general statement "View # institutions with # reports" directly under the Country name header. This should link to a filtered results list of institutions by country.

THIS IS A FILTERED LIST OF INSTITUTIONS IN THE COUNTRY WITH REPORTS.  LIST THE NUMBER OF COUNTRY-BASED INSTITUTIONS WITH REPORTS AS WELL AS THE NUMBER OF REPORTS.

- Include statement "View # institutions with # reports" under each agency name at the bottom of the Country page. This should link to a filtered list of institutions by country and agency.

THIS IS A FILTERED LIST OF INSTITUTIONS IN THE COUNTRY WITH REPORTS BY A PARTICULAR AGENCY.  LIST THE NUMBER OF COUNTRY-BASED INSTITUTIONS WITH AGENCY'S REPORTS AS WELL AS THE NUMBER OF REPORTS.

**Comment by Gyukat** [comment]
So, reviewing what I can see in the test...the agency filters look okay but the country filters don't make sense to me.
To be clear, we need to know:
1a) The number of institutions with reports in the country
1b) The number of reports about institutions in the country

2a) Based on list of agencies who work in the country (derived from "official" and "unofficial" focus country in agency records--which should be based in part on the reports generated), list how many reports for each agency about how many institutions in the country.  (ONLY REPORTS ABOUT INSTITUTIONS IN THAT COUNTRY)

**Comment by Gyukat** [comment]
I didn't really get your question but I hope it was answered by the above...

**Comment by ctueck** [comment]
I'm just reopening this one with a view to integrating `/stats/by-agency/{id}` into `/browse/agencies/{id}` and `/stats/by-country/{id}` into `/browse/countries/{id}` and `/browse/agencies/focusing-to/{id}`, per our phone discussion 2 or 3 weeks ago.

**Comment by Gyukat** [comment]
Yes, wondering what is happening on this...it is important!  Here is the card in trello: https://trello.com/c/IZrC1Hzo

**Comment by JoshBone** [comment]
So I've included the counters. 
On every included endpoint they're called 'report_count' and 'institution_count'. 
Currently it only lists "directly" connected institutions, the fully accurate numbers are coming when I'll finish solr.

**Comment by ctueck** [comment]
Looks good on the test!

Just one counter seems to be entirely wrong, `institution_count` in `browse/agencies/focusing-to/{id}/` - it's always identical to `report_count`.

**Comment by JoshBone** [comment]
Ah... Silly me! I forgot to add 'distinct' to the Institution counter.
