### ISSUE TITLE
Country page - Agency entry expanded

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#232]
We will need to expand the country record to include more information on the agencies:

For this we will need to bring in: 

1) agency registration dates 
(For the registration dates, we will show the registered_from date with an open end point for those that are still registered, e.g. 2009-  .  I think this is part of the display programming, right?)

2) whether agency is officially working in this country.

**Comment by JoshBone** [comment]
Which endpoint are we talking about?

**Comment by Gyukat** [comment]
/browse/agencies/focusing-to/{countryID}/  This would be used to generate a list of agencies operating in the country.  We need to add both agency.registration_start and registration_valid_to dates and agencyfocuscountry.is_official status.

**Comment by JoshBone** [comment]
https://backend.deqar.eu/webapi/v1/browse/agencies/focusing-to/141/

**Fields added:** `country_is_crossborder`, `registration_start`, `registration_valid_to`

Swagger updated!

**Comment by Gyukat** [comment]
It should be `country_is_official`...not "crossborder"

you can leave cross border if you like.  We may use it someday.

**Comment by JoshBone** [comment]
Whoops...
I'm sorry. I was reading the country_is_crossboarder filter issue right before this. :)
Fixed!

**Comment by Gyukat** [comment]
Got it!
