### ISSUE TITLE
Search Funtionality compromised

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#239]
I will list here the searches for known institutions that did not work:

- I tried search “Universitat Politècnica de Catalunya” and for some reason it didn't work, even when I cut and paste the name from the record.  I also tried just the term “politecnica” with and without diacrtitics, and it didn't work.
-  I tried to search “School of Industrial, Aerospace and Audiovisual Engineering of Terrassa” and for some reason it didn't work, even when I cut and paste directly from the hits list. 
- I tried to search “Besançon” with and without diacritics and it didn't work.
- I tried search “Université Bourgogne – Franche-Comté” as well as “Franche Comte”, “Franche Comté” “Franche-Comte” and “Franche-Comté” and for some reason these didn't work, even when I cut and paste the name or term from the record. 
- I tried search “ESPE de l'académie de Dijon” which as expected did not produce hits, but the search box came back with this value multiple times “ESPE de l\'académie de Dijon”.
- I tried to search “Faculty of Translation and Interpretation” and “Translation and Interpretation” but got no hits.

For most of these I could finally reach success by choosing only one term of a phrase or choosing another term, but most end users wouldn't go through that.

**Comment by Gyukat** [comment]
I have added the Slik label in case it is actually a bug on their end.  (Probably the case.)

**Comment by JoshBone** [comment]
I've tried the things in the backend and it seems fine. 
https://backend.deqar.eu/webapi/v1/browse/institutions/?query=Universitat+Polit%C3%A8cnica+de+Catalunya&agency=&esg_activity=&country=&qf_ehea_level=&status=&report_year=&focus_country_is_crossborder=&history=
https://backend.deqar.eu/webapi/v1/browse/institutions/?query=School+of+Industrial%2C+Aerospace+and+Audiovisual+Engineering+of+Terrassa&agency=&esg_activity=&country=&qf_ehea_level=&status=&report_year=&focus_country_is_crossborder=&history=

I can imagine, that they are not URLEncoding the query string that they're sending...

**Comment by Gyukat** [comment]
Before I send it through to them, can you confirm that all the institution name fields + city + country are searched to make sure it is not a problem of the search domain?  

They claim to have already URL encoded the search.
<img width="634" alt="screen shot 2018-08-02 at 14 34 20" src="https://user-images.githubusercontent.com/33084539/43583910-32971800-9661-11e8-93b1-580c77faa733.png">

**Comment by JoshBone** [comment]
Okay...
So I'm checking the log now. 

1) 'Universitat Politècnica de Catalunya' should be passed as in the url query param as:
* `Universitat+Politècnica+de+Catalunya`, or
* `Universitat%20Politècnica%20de%20Catalunya`

In the log I can see that it's passed as:
`Universitat%2BPolit%25C3%25A8cnica%2Bde%2BCatalunya`
which can be decoded as:
`Universitat+Polit%C3%A8cnica+de+Catalunya`

So apparently, there is some UTF-8 issue on the frontend when the query string contains UTF-8 characters. 

2) 'School of Industrial, Aerospace and Audiovisual Engineering of Terrassa' should be passed as:
* `School+of+Industrial%2C+Aerospace+and+Audiovisual+Engineering+of+Terrassa`
* `School%20of%20Industrial%2C%20Aerospace%20and%20Audiovisual%20Engineering%20of%20Terrassa`

In the log it appears as:
`School%2Bof%2BIndustrial%252C%2BAerospace%2Band%2BAudiovisual%2BEngineering%2Bof%
2BTerrassa`
which can be decoded as:
`School+of+Industrial%2C+Aerospace+and+Audiovisual+Engineering+of%
2BTerrassa`

Here there is an extra %2B, which is the URLEncoded form of '+'. 

So I think there are problems with parsing the query string if it contains UTF-8, plus also there are problems URLEncoding correctly. 

I would advise them in the first place to try skip the URLEncoding but take care of the UTF-8 characters.

**Comment by Gyukat** [comment]
You can close this, right?
