### ISSUE TITLE
Country record formatting

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#240]
We are trying to use the bold, italics and paragraphing that seem to be available through the backend.  Only some of the formatting seems to carry through to the front end.

We have tried:
- for bold = b and strong
- for italics = i and em
- for paragraphing = p and br

Not really working.

<img width="733" alt="screen shot 2018-08-03 at 17 15 26" src="https://user-images.githubusercontent.com/33084539/43650900-401a3bb6-9741-11e8-920e-75a7fa5d992e.png">
<img width="871" alt="screen shot 2018-08-03 at 17 15 49" src="https://user-images.githubusercontent.com/33084539/43650897-3fee7b52-9741-11e8-85db-eab8ce6a2c57.png">
<img width="911" alt="screen shot 2018-08-03 at 17 15 37" src="https://user-images.githubusercontent.com/33084539/43650898-4004b2e6-9741-11e8-9904-df5564025e09.png">

**Comment by JoshBone** [comment]
I'm giving back the proper html string on the API endpoint:
https://backend.deqar.eu/webapi/v1/browse/countries/17/

Can you ask Slik how they parse the string back? 
It might be that they use some html parser, which simply omits html tags.

**Comment by Gyukat** [comment]
Slik card: https://trello.com/c/ecGvcYy5

Close this!
