### ISSUE TITLE
URGENT!!! add joint programme data to end point

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#248]
We need two different fields added to the institution / PROGRAMME reports.  We should know:
- if the programme is a joint programme (yes/no).
- the name of the other (1....n) institutions that share the programme.  (It is usually one other, but it could theoretically be more.)

**Comment by JoshBone** [comment]
So, let me just phrase it... 
If a programme level report is submitted under the AgencyActivityType joint programme, then I should collect the other institution names... How are those institutions are joined?

**Comment by JoshBone** [comment]
Oh geez... Ignore my previous ones. 😸 
Somehow my mind is still wrapping around institution relationships. 

So basically what we need here is an indicator of the ESGActivity type + the list of institutions joined to the report.

**Comment by JoshBone** [comment]
One important question... 
Should I only list the "extra" institutions?

**Comment by JoshBone** [comment]
Fields were added: 
`institutions` - A list of institution entries, excluding the one from which the information was requested (in the URL param)
`agency_esg_activity_type` - This can one of the four values defined in the database: 'programme', 'institutional', 'joint programme', 'institutional/programme'

Deployed to backend.test!

**Comment by Gyukat** [comment]
Hey Josh, somehow I didn't see the notes on these in my email.  Sorry for the delay...

So, yes, we need the institutions associated with Joint Programme type.  
You can include or exclude (as you have chosen) the original institution.  (It is good to keep separate and they can get the original institution from elsewhere if they like...)

Will check test...don't quite understand what you were saying about activity type above.

**Comment by Gyukat** [comment]
Josh, can we move this to the final version now...I would like Slik to complete their work.
