### ISSUE TITLE
endpoint for chronological list of EQAR decisions

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#265]
It would be nice to have an endpoint that returns a chronological list of EQAR decisions on agencies.

See the page <https://www.eqar.eu/register/decisions/>, I'd prefer to make this generated live from the backend.

**Comment by JoshBone** [comment]
https://backend.deqar.eu/webapi/v1/browse/agencies/decisions/

Is it okay like this, or should I extract the years as well?

**Comment by ctueck** [comment]
Looks good, thanks! I can group by year in the template, sufficient as is.

In principle, this could also be paged, especially when the list grows. But we can keep that for web API v2 - we might in general review which endpoints should return paginated results and which not.
