### ISSUE TITLE
Data Model modifications

### ISSUE THREAD

**Issue by JoshBone** [EQAR/eqar_backend#272]
Content fields that need to be added to the Report in DM:

Comment
NEW! Narrative Report Summary
Content table that need to be added to the Report in DM:

Partner Agency
Administrative field that need to be added to the Report in DM:

Event Tracking <date/time stamp> >> on "save record"
Event Tracking Note
Internal Note

**Comment by JoshBone** [comment]
Questions about the fields:
- Comment - **Should this field to be available on the submissionAPI and CSV import as well?**
- Narrative Report Summary - **Should this field to be available on the submissionAPI and CSV import as well?**

Partner Agency - ** How this field should behave? How it is affecting the current submission, validation and webAPI behaviour? Is this a one-to-one or one-to-many field?

Event Tracking <date/time stamp> >> on "save record" - **Will records be timestamped, if they are modified through the API/CSV as well?**

**Comment by Gyukat** [comment]
The two fields will appear on the API and CSV as far as I understand.  We can discuss this along with pipeline questions after the first phase of Admin UI updates are finished.

The field WILL affect the submission and validations as I understand.  For instance, the "official" status in a country can be in EITHER one OR the other agency OR BOTH.  The activities will still be from the submitting country.  

We should look at how it affects report counts on the different websites, especially if the activity is not assigned.

I think records should be timestamped through API/CSV

**Comment by Gyukat** [comment]
@ctueck imput.  
Responses: 

 1. YES, all comment and summary fields should be open to API and CSV.
 2. YES, timestamping should also occur when record is uploaded/changed via API or CSV

Partner Agencies is more tricky:

 1. Partner Agency is One-to-Many, i.e. one report may have several partner agencies (but only one "main").  *(KM: I think it is many-to-many as one partner agency may be on several reports; the field is also repeatable, but of course the agencies already listed as main or partner should not be allowed to be entered twice.)*
 2. Validation Rules: I [Colin] see two approaches in principal, either that any involved QAA may satisfy or that only the main QAA is checked (and has to satisfy the conditions). but maybe it depends on the type of check...
 3. "official reports only in countries where QAA has official status" (red flag): here a) we could argue  that it should refer to the main QAA, to make sure that the one (or one of the QAAs) that are actually cleared for the country take responsibility for the report BUT B) we could also say that the report clears if any of the QAAs has official status. *(KM: Given the situation with Musique, I would vote for B.)*
 4. "new countries" (yellow flag): here i can see a point that all involved QAAs trigger the flag (and countries should be added for all involved QAAs, as they were all "active" if they carry out a review).
 5. one could argue that partner agencies should actually include a link to a specific activity (of that agency), but i think it's unnecessarily complex and too difficult for (agency) users.  *(KM: How will we link the partner agency reports to the agency page activities section in the system?  We probably should have them assign an activity to do it right.)*
 6. especially #3 opens the question whether there are proxies/limitations for declaring partner agencies involved - but also for this one, I think it's not needed and too complex. but I'd suggest that partner agencies should receive a copy of the submission email, so they know at least.

I think other validation rules in the pipeline do not relate to the agency and should remain unaffected, no?
