### ISSUE TITLE
Web API: programme level report list ordering principle

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#278]
/browse/reports/programme/by-institution/{id}/ 

We need to order the entries by programme name as the primary  (already done) AND by QF-EHEA level as the secondary ordering principle.  It needs to go short cycle, first cycle, second cycle, third cycle and other--in that order.

**Comment by ctueck** [comment]
Not possible with the current logic of the result list: it's report-oriented, one report might have several programmes, hence ordering by programme name not doable.

Might be taken up by entirely new programme-oriented endpoint.
