### ISSUE TITLE
QF-EHEA level "other"

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#279]
The level "other" should not be used for institutions.  When it is used for programmes, we need to remove the sanity check that compares it with the QF levels assigned to the institution.  "Other" is an exception and should not be checked.

**Comment by ctueck** [comment]
General review of validation/flagging needed, should be considered as part of that.

Additionally, forthcoming changes for micro-credentials and alternative providers might resolve necessity of "other" altogether.
