### ISSUE TITLE
Agency name requirements

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#281]
The current structure of Agency names is that there is one and only one required primary name and acronym for each agency.   (We may have to revisit this requirement, but let's assume for the moment that it still stands.)

In Django, it is currently possible to mark more than one agency acronym and more than one agency name as primary.  This should be disallowed.

We also have a problem with the display, but we think it can be fixed in the templates.

**Comment by ctueck** [comment]
Ensured in the Admin UI, so no urgent need to enforce this constraint in Django.

Additionally, logic of retiring agency names in Admin UI addressed by https://github.com/EQAR/deqar_frontend/issues/86
