### ISSUE TITLE
Submission log: distinguish between API and admin UI

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#282]
In the submission package log, use of the API (directly by external users) and the admin UI are not easily distinguishable, as both are identified as `api` (due to admin UI using the same submission API, understandably).

Could we find some way to make them distinguishable for debugging and statistical purposes?

**Comment by JoshBone** [comment]
I've added a check for the 'HTTP ORIGIN' header and if that includes 'deqar.eu' then the request is coming form the server, so it should be a form submission, otherwise it's an API. 

Check submission log entry '3504' on test which I've created just now via Submission form.
