### ISSUE TITLE
WebAPI differing hierarchical relationships

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#286]
There are two different sorts of hierarchical relationship: faculty and consortium.

The current behaviour is fine for faculty.

For consortium, one change is needed.  We should not show the relationship in the general results list.  Currently, it is shown in the results list as:

 <parent> / <child>

Now it should be shown separately as :

<parent> 
...
<child>

_(Note, the links between the two records AND THE CASCADING REPORTS may remain in the institution record....unless we say otherwise.  For now there have been no complaints about this.)_

**Comment by ctueck** [comment]
It's fine how this is returned in WebAPI v1 now. Should be the same in v2, but I close this issue as I included that in issue #292.
