### ISSUE TITLE
/browse/countries/by-reports: add counters

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#291]
Please add these counts per country:

- institutions total (all, incl. those with no reports)
- institutions ETER (number of institutions coming from ETER, incl. those with no reports)
- reports total (on institutions in country)

In addition, could you add a flag per country signalling whether we have a comprehensive HEI list (from ETER or elsewhere), and return that flag in this endpoint?

(All this for producing a heatmap.)

**Comment by ctueck** [comment]
Counters work nicely already, see heatmap at https://test.eqar.eu/qa-results/search/

Could we actually have two new variables at country level:
1. Has comprehensive HEI list (see above, from ETER or elsewhere) - simple boolean yes/no - could be called `has_full_institution_list` or something like that
2. Fulfils EHEA key commitment - the same 3-level scale as for _External QAA is permitted_ and _European approach is permitted_, i.e. _yes_, _partially / with conditions_ or _no_ - could be called `ehea_key_commitment` for example.

**Comment by JoshBone** [comment]
Hi,

I've added the two new fields to the model. 
It can be set in the Django Suit.

I also added the fields to the 'country-list' and 'country-detail' endpoints. 
Do you also need these ones here at 'country-list-by-reports'?

**Comment by ctueck** [comment]
Yes, I think I will probably need them here, too, so please add. (I suppose it doesn't make any real performance difference.)

**Comment by JoshBone** [comment]
Deployed to test, you can test it.

**Comment by ctueck** [comment]
Looks all great, closing this.
