### ISSUE TITLE
/browse/institutions : faceted search and enhancements

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#292]
For the new version 2, here's a first list of changes and enhancements:

- Results should be paginated, like in version 1.
- Hierarchical relationships should be included, similar to version 1 - we don't need all data in the result list, mainly the name and relationship type.
- Is it possible to use IDs (for countries, agencies, ...) in the parameters?
- For text search, could we match words with missing diacritics (e.g. `universite` matches `université` or `dusseldorf` matches `düsseldorf`) or even slightly differently spelled words?
- When using filters, the results are ordered alphabetically, which is good, but for instance in Finland `Å` comes after `Z`, instead of between `A` and `B` (which is where it comes in v1, and I suppose that's how it should be).
- Results returned:
    - `eter_id` should be the actual ID, e.g. `HR0026`, not the internal numerical ID.
    - Could we get country separate from city, like in v1?
    - add QF EHEA levels if possible
    - add institution's `name_official`

Here are the facets we should have for the facetted search:
- Agency
- ESG activity
- Country
- QF EHEA level (of the institution)
- Status (voluntary vs part of ..., i.e. at least one report of the chosen status)
- Cross-border (i.e. at least one report that is considered cross-border according to flag in agency focus country table - see also discussion in #216 )

**Comment by JoshBone** [comment]
The signals are not deployed yet. :)

Definition for the available filter options are here: https://backend.test.deqar.eu/webapi/v2/swagger/

**Comment by ctueck** [comment]
As `name_official` this currently returns an array with all historical names, I guess this is so that search also can find by previous names?

For results we only need the current official name. Either skip the others, or is the last element by convention the currently valid one?

**Comment by ctueck** [comment]
As noted, there's one issue with `name_official`, see comment above: it is nice that you can also find institutions by previous names, but it would be helpful to see in results which is the current official name (for display).

As mentioned, faceted search works really nice!

One facet doesn't seem to work, the activity type - the numbers seem about right, but whatever you apply you get 0 results.

In the QF EHEA levels returned, could you order them short cycle, first cycle, second cycle, third cycle, please? (I think that's also in order of their codes/IDs.)

Two issues are still open otherwise:

- For text search, is it possible to match when missing diacritics (e.g. universite matches université or dusseldorf matches düsseldorf) or even slightly differently spelled words?
- In alphabetic sort, in Finland Å comes after Z, instead of between A and B (which is where it comes in v1, and I suppose that's how it should be). Other example: *É*cole comes after Z, too.

**Comment by JoshBone** [comment]
> For text search, is it possible to match when missing diacritics (e.g. universite matches université or dusseldorf matches düsseldorf) or even slightly differently spelled words?
This should be fine, see a search for 'hogskolan' which should give results to 'Högskolan på Åland'.

**Comment by JoshBone** [comment]
> In alphabetic sort, in Finland Å comes after Z, instead of between A and B (which is where it comes in v1, and I suppose that's how it should be). Other example: École comes after Z, too.

Fixed. I had to change the solr configuration:
https://backend.test.deqar.eu/webapi/v2/browse/institutions/?query=&country=Finland&ordering=name_sort&limit=50

**Comment by JoshBone** [comment]
> As noted, there's one issue with name_official, see comment above: it is nice that you can also find institutions by previous names, but it would be helpful to see in results which is the current official name (for display).

I included a field called `name_official_display` which only contains the name_official value when valid_to date is not set. (There are couple of records in the beginning, which don't have this field. This is due that we were/are testing the institution form and there were some bugs )
