### ISSUE TITLE
/browse/institutions/{id}/ : missing details

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#293]
1. It would be great if the endpoint could support looking up the institution using the ETER ID if it has one.

2. For the info on `hierarchical_relationships`, please include the relationship type and the dates (so we can distinguish current and historic ones).

**Comment by JoshBone** [comment]
I made a new endpoint supporting ETER ID queries:
https://backend.test.deqar.eu/webapi/v2/browse/institutions/by-eter/AT0008/
(It renders the same output as the regular one)

Plus the date and type should be included.

**Comment by ctueck** [comment]
Lookup via ETER ID seems to work well.

But I seem to get a 500 error each time I try to open an institutions involved in some hierarchical relationships, whether via ETER ID or via DEQARINST ID.

**Comment by ctueck** [comment]
The type and dates of the hierarchical relationships are still missing:

![grafik](https://user-images.githubusercontent.com/37637883/60844948-2c05d400-a1db-11e9-9b82-aaf036f3d37f.png)

(Included for 2nd level, but not for the direct relationships.)

**Comment by JoshBone** [comment]
I removed the 2nd level information (it's more resource friendly this way) and included the relationship type and dates for hierarchical relationships.

Check here:
https://backend.test.deqar.eu/webapi/v2/browse/institutions/820/

**Comment by ctueck** [comment]
Looks good, thx.
