### ISSUE TITLE
browse/reports/*/by-institution/{id}/ : additional data

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#294]
For the two endpoints returning report lists, please include:

- the relationship type in the `institutions` array (e.g. like in hierarchical relationships table or something else if the relationship is a joint report or through the historical link)
- `institution_relationship_context` can be removed
- the report ID

**Comment by JoshBone** [comment]
Can I separate the directly related, the historically and hierarchically related institutions? It might be more resource-friendly. :)

**Comment by ctueck** [comment]
Yes, definitely. That'll probably also make it more straight-forward to use in the frontend. :)

Please also add this info in the same way to the single report endpoint, re. issue #295

**Comment by JoshBone** [comment]
https://backend.test.deqar.eu/webapi/v2/browse/reports/programme/by-institution/820/
Please check!

(The programme info is also embedded in the reports section, but it's the same. I'm using now the same serializer as for the report-detail endpoint, that's why...)

**Comment by ctueck** [comment]
Actually you could simplify the serializer further and omit `institutions_hierarchical` and `institutions_historical`. They merge the relationships of all institutions to which the report applies, so it's of limited use.

And the relationships of the current institution I anyway have at hand, so I am now using that to figure out which of the institutions covered by a report is a related one to the current.

Maybe this will even increase performance. ;)
