### ISSUE TITLE
/browse/reports/{id} : new endpoint

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#295]
We need a new endpoint that returns the data on one single report, identified by its ID.

(Path can be changed if you think something else is more logical.)

The return data should be the same same data as in `/browse/reports/*/by-institution/{id}/`, of course with data on all institutions (the existing endpoints exclude the institution via which you searched).

**Comment by JoshBone** [comment]
In this endpoint do you need also institutions which are not directly related to report, but through historical/hierarchical relationships?

**Comment by JoshBone** [comment]
https://backend.test.deqar.eu/webapi/v2/browse/reports/2345/

**Comment by ctueck** [comment]
Yes, would be great to add the info on related institutions, so we can show it on the page. Could be returned in the same way/structured as we discussed under #294

**Comment by JoshBone** [comment]
Do you think it can work like this? 
Hierarchical institutions:
https://backend.test.deqar.eu/webapi/v2/browse/reports/8627/

Historical institutions:
https://backend.test.deqar.eu/webapi/v2/browse/reports/4825/

The question is... 
Should I filter out the historical ones to which the report is not applicable (the relationship_date is outside the reports validity period?) or you would like to do it on the frontend?

**Comment by Gyukat** [comment]
I think the institution records should be "stable"...so I wouldn't change the display too widely from report to report--e.g. based on the report dates.
