### ISSUE TITLE
/browse/reports : new endpoint to search reports

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#296]
For the advanced search we'd like a new endpoint that searches directly for reports, i.e. not via institutions.

It should support these search parameters, preferably all as facets for drilling down as well:
  * Agency
  * ESG activity
  * Activity type (i.e. institution, programme, joint programme, ...)
  * Country (of institution on which the report is)
  * Status (voluntary vs part of ...)
  * Decision
  * Cross-border (based on cross-border flag in agency focus country table; multi-institution reports should be considered cross-border if they are cross-border for at least one of the institutions)
  * Report date range
  * Validity date range (for date ranges I don't know how faceted search could work, maybe by year?)

The result list should include:
  * Institution(s) name, ID, country
  * Programme name(s), if applicable
  * Agency
  * ESG activity
  * Status
  * Decision
  * Cross-border status
  * Report date and validity date

Sort order should be customisable by:
  * Report date
  * Validity date
  * Institution name
  * Institution country
  * Agency

**Comment by JoshBone** [comment]
Sorting can only be applied for fields which has only one value... There can be more institutions + institution countries. :)

**Comment by ctueck** [comment]
Indeed, good point. :) So the only way would be to duplicate rows for each institution, but that's maybe rather the point of the search via institutions. Let's leave those sort options for the time being then.

**Comment by ctueck** [comment]
One more parameter should be included, as filter and search facet: the report language.

**Comment by JoshBone** [comment]
So... I'm thinking... That if we do this endpoint (and here we don't need to search inside institution names...) I can rechannel the two endpoints: 
browse/reports/programme/by-institution/
browse/reports/institutional/by-institution/
because basically they are just different filters... 
What do you think?

**Comment by ctueck** [comment]
Just to confirm response from Slack: yes, fully agree, replacing the two existing endpoints by filters on this one is fine with me.

One thing: search for programme reports needs to include joint programmes, too. That should be a general rule for filters by report type: if a user searches for programme reports they don’t want to exclude joint programmes, but if they select "joint programmes", it should be joint programmes only.

**Comment by JoshBone** [comment]
Hey,
Please check the endpoint, I'm pretty sure that there will be additional tweaks.

**Comment by ctueck** [comment]
Looks very good! See https://test.eqar.eu/qa-results/search/by-report/

Main issue is that `.../reports/*/by-institution/{id}/` and `.../reports/{id}` seem to have been "hidden".

Otherwise can see only one issue: the language facet doesn't work, always leads to 500 errors.
