### ISSUE TITLE
URLs to report files should be https://...

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#350]
This endpoint only returns the path to the report file `/reports/AGENCY/...`, but doesn't include `https://backend.deqar.eu`. Should be added for consistency.

(The other endpoints returning report file info do provide a full URL.)

**Comment by ctueck** [comment]
Looks good. But I realise a related issue: all file URLs (also in other endpoints) are currently given as HTTP URLs. Is there a way to tell Django it's behind a reverse proxy and make it return HTTPS URLs as a rule?

**Comment by ctueck** [comment]
The report file URLs are still all http://... instead of https://...

**Comment by JoshBone** [comment]
Changed the SECURE_PROXY_SSL_HEADER in the settings.
