### ISSUE TITLE
Submission API: wrong schema definition

### ISSUE THREAD

**Issue by kogelnikp** [EQAR/eqar_backend#362]
Hi everyone,

I found a small mismatch in the definition of your submission API.
In ResponseReportSuccessResponseSerializer the fields `institution_warnings` and `report_warnings` are defined as CharField:
https://github.com/EQAR/eqar_backend/blob/8bde2ba084d1e34b34f4bba32fcb15763d04d95f/submissionapi/serializers/response_serializers.py#L62-L63

But the actual responses inside these two fields are string arrays:
https://github.com/EQAR/eqar_backend/blob/8bde2ba084d1e34b34f4bba32fcb15763d04d95f/submissionapi/views/submission_report_view.py#L106-L107

Unfortunately, the CharField definition leads to a wrong Swagger/OpenAPI schema being generated:
![grafik](https://user-images.githubusercontent.com/8058487/106878453-44e9aa80-66da-11eb-932c-e32f58e7084c.png)

With this mismatch it's not possible to auto-generate a client out of the schema definition any more.
So the field definitions in the Serializer should be changed to string arrays.

**Comment by JoshBone** [comment]
Thanks for the proper description.
I'll commit a fix.
