### ISSUE TITLE
wrong warning in email after submitting report

### ISSUE THREAD

**Issue by kogelnikp** [EQAR/eqar_backend#402]
Hi everyone,

I found a bug when resubmitting a previously deleted report via the submission API.
When deletion for a report is requested, a flag is assigned which says "Deletion was requested.".

After resubmitting the report, the flag is, as expected, not present in the admin ui any more. 
But in the email which is sent after submitting a report, the flag "Deletion was requested" is still listed as a warning:
![image](https://user-images.githubusercontent.com/8058487/127275581-3baeffd9-0f21-47a3-9ef7-da575286a12d.png)

I think I've already found the cause for it:
When resubmitting a report the flags are not actually deleted, but only set to inactive.
https://github.com/EQAR/eqar_backend/blob/309b657f7d8ecf13a46d9fb67f25f506a508c028/submissionapi/flaggers/report_flagger.py#L39-L44

In the code where the email is generated all flags are loaded, regardless if they are active or not:
https://github.com/EQAR/eqar_backend/blob/309b657f7d8ecf13a46d9fb67f25f506a508c028/submissionapi/views/submission_report_view.py#L107

The same applies for the CSV upload:
https://github.com/EQAR/eqar_backend/blob/3a0c7c1fab2e1dbc0cd52eb17c8a75707c5692ab/submissionapi/views/csv_upload_report_view.py#L73

There needs to be some kind of restriction on which flags to show in the email.

**Comment by JoshBone** [comment]
Thank you!
Indeed. We extended the models of the flag in a way, that when EQAR removes a flag it won't be triggered once again (hence the active status) but I forgot to filter them out from the notifications. Excellent catch! :)
