### ISSUE TITLE
Flagging: official status check also for voluntary reports

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#476]
<https://github.com/EQAR/eqar_backend/blob/7007c10c044a0a428c1fb8b8c71d25fc73a3da4d/submissionapi/flaggers/report_flagger.py#L122>

The flagger currently runs the check whether the agency has "official status" in at least one institution's country for **all** reports, but it should only run for reports with status "part of the obligatory ...".

**Comment by JoshBone** [comment]
Fixed by #483
