### ISSUE TITLE
Problem generating Verifiable Credential

### ISSUE THREAD

**Issue by pedromxavier14** [EQAR/eqar_backend#513]
When I try to generate a Verifiable credential using DEQAR format I got this error:

<img width="2051" alt="Captura de ecrã 2024-05-22, às 17 34 45" src="https://github.com/EQAR/eqar_backend/assets/142126278/f4e6ed86-a22d-4ce9-b2a1-730221c368a8">

**Comment by ctueck** [comment]
Thanks for creating the issue. There was an issue with the SSIkit backend that DEQAR uses to sign credentials, it's now back and things are working again.
